// Mocks generated by Mockito 5.4.4 from annotations
// in ai_flutter/test/unit/features/profile/domain/use_cases/update_address_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ai_flutter/core/models/address.dart' as _i3;
import 'package:ai_flutter/core/models/user.dart' as _i2;
import 'package:ai_flutter/features/profile/domain/repositories/profile_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddress_1 extends _i1.SmartFake implements _i3.Address {
  _FakeAddress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i4.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.User>);

  @override
  _i5.Future<_i2.User> updateProfile({
    String? fullName,
    String? email,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #fullName: fullName,
            #email: email,
            #avatarUrl: avatarUrl,
          },
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #updateProfile,
            [],
            {
              #fullName: fullName,
              #email: email,
              #avatarUrl: avatarUrl,
            },
          ),
        )),
      ) as _i5.Future<_i2.User>);

  @override
  _i5.Future<List<_i3.Address>> getAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getAddresses,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Address>>.value(<_i3.Address>[]),
      ) as _i5.Future<List<_i3.Address>>);

  @override
  _i5.Future<_i3.Address> addAddress({
    required String? recipientName,
    required String? phoneNumber,
    required String? streetAddress,
    required String? ward,
    required String? district,
    required String? city,
    bool? isDefault = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAddress,
          [],
          {
            #recipientName: recipientName,
            #phoneNumber: phoneNumber,
            #streetAddress: streetAddress,
            #ward: ward,
            #district: district,
            #city: city,
            #isDefault: isDefault,
          },
        ),
        returnValue: _i5.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #addAddress,
            [],
            {
              #recipientName: recipientName,
              #phoneNumber: phoneNumber,
              #streetAddress: streetAddress,
              #ward: ward,
              #district: district,
              #city: city,
              #isDefault: isDefault,
            },
          ),
        )),
      ) as _i5.Future<_i3.Address>);

  @override
  _i5.Future<_i3.Address> updateAddress({
    required String? addressId,
    String? recipientName,
    String? phoneNumber,
    String? streetAddress,
    String? ward,
    String? district,
    String? city,
    bool? isDefault,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAddress,
          [],
          {
            #addressId: addressId,
            #recipientName: recipientName,
            #phoneNumber: phoneNumber,
            #streetAddress: streetAddress,
            #ward: ward,
            #district: district,
            #city: city,
            #isDefault: isDefault,
          },
        ),
        returnValue: _i5.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #updateAddress,
            [],
            {
              #addressId: addressId,
              #recipientName: recipientName,
              #phoneNumber: phoneNumber,
              #streetAddress: streetAddress,
              #ward: ward,
              #district: district,
              #city: city,
              #isDefault: isDefault,
            },
          ),
        )),
      ) as _i5.Future<_i3.Address>);

  @override
  _i5.Future<void> deleteAddress(String? addressId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAddress,
          [addressId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Address> setDefaultAddress(String? addressId) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDefaultAddress,
          [addressId],
        ),
        returnValue: _i5.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #setDefaultAddress,
            [addressId],
          ),
        )),
      ) as _i5.Future<_i3.Address>);
}
