"""Create vouchers table

Revision ID: 297eb0370c78
Revises: ca608a4c3040
Create Date: 2025-12-05 16:50:47.619904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297eb0370c78'
down_revision: Union[str, Sequence[str], None] = 'ca608a4c3040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PERCENTAGE', 'FIXED_AMOUNT', name='vouchertype'), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('min_order_value', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('max_discount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_code'), 'vouchers', ['code'], unique=True)
    op.create_index('ix_vouchers_code_active', 'vouchers', ['code', 'is_active'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index('ix_vouchers_shop_active', 'vouchers', ['shop_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_vouchers_shop_id'), 'vouchers', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vouchers_shop_id'), table_name='vouchers')
    op.drop_index('ix_vouchers_shop_active', table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index('ix_vouchers_code_active', table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_code'), table_name='vouchers')
    op.drop_table('vouchers')
    # ### end Alembic commands ###
