// Mocks generated by Mockito 5.4.4 from annotations
// in ai_flutter/test/unit/features/cart/domain/use_cases/add_to_cart_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ai_flutter/core/models/cart_item.dart' as _i2;
import 'package:ai_flutter/core/models/product.dart' as _i5;
import 'package:ai_flutter/features/cart/domain/repositories/cart_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCartItem_0 extends _i1.SmartFake implements _i2.CartItem {
  _FakeCartItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i3.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CartItem>> getCart(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCart,
          [userId],
        ),
        returnValue: _i4.Future<List<_i2.CartItem>>.value(<_i2.CartItem>[]),
      ) as _i4.Future<List<_i2.CartItem>>);

  @override
  _i4.Future<List<_i5.Product>> getProductsForCart(List<String>? productIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsForCart,
          [productIds],
        ),
        returnValue: _i4.Future<List<_i5.Product>>.value(<_i5.Product>[]),
      ) as _i4.Future<List<_i5.Product>>);

  @override
  _i4.Future<_i2.CartItem> addToCart({
    required String? userId,
    required String? productId,
    String? variantId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [],
          {
            #userId: userId,
            #productId: productId,
            #variantId: variantId,
            #quantity: quantity,
          },
        ),
        returnValue: _i4.Future<_i2.CartItem>.value(_FakeCartItem_0(
          this,
          Invocation.method(
            #addToCart,
            [],
            {
              #userId: userId,
              #productId: productId,
              #variantId: variantId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i4.Future<_i2.CartItem>);

  @override
  _i4.Future<_i2.CartItem> updateQuantity({
    required String? cartItemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [],
          {
            #cartItemId: cartItemId,
            #quantity: quantity,
          },
        ),
        returnValue: _i4.Future<_i2.CartItem>.value(_FakeCartItem_0(
          this,
          Invocation.method(
            #updateQuantity,
            [],
            {
              #cartItemId: cartItemId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i4.Future<_i2.CartItem>);

  @override
  _i4.Future<void> removeCartItem(String? cartItemId) => (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [cartItemId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCart(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> syncCart(
    String? userId,
    List<_i2.CartItem>? localItems,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncCart,
          [
            userId,
            localItems,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
