// Mocks generated by Mockito 5.4.4 from annotations
// in ai_flutter/test/unit/features/cart/domain/use_cases/apply_voucher_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ai_flutter/core/models/cart_item.dart' as _i6;
import 'package:ai_flutter/core/models/order.dart' as _i2;
import 'package:ai_flutter/core/models/voucher.dart' as _i3;
import 'package:ai_flutter/features/cart/domain/repositories/order_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrder_0 extends _i1.SmartFake implements _i2.Order {
  _FakeOrder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoucher_1 extends _i1.SmartFake implements _i3.Voucher {
  _FakeVoucher_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i4.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Order>> createOrder({
    required String? userId,
    required List<_i6.CartItem>? items,
    required String? addressId,
    required String? paymentMethod,
    String? voucherCode,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #userId: userId,
            #items: items,
            #addressId: addressId,
            #paymentMethod: paymentMethod,
            #voucherCode: voucherCode,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
      ) as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<List<_i2.Order>> getOrders({
    required String? userId,
    String? status,
    int? limit,
    String? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #userId: userId,
            #status: status,
            #limit: limit,
            #cursor: cursor,
          },
        ),
        returnValue: _i5.Future<List<_i2.Order>>.value(<_i2.Order>[]),
      ) as _i5.Future<List<_i2.Order>>);

  @override
  _i5.Future<_i2.Order> getOrderDetail(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrderDetail,
          [orderId],
        ),
        returnValue: _i5.Future<_i2.Order>.value(_FakeOrder_0(
          this,
          Invocation.method(
            #getOrderDetail,
            [orderId],
          ),
        )),
      ) as _i5.Future<_i2.Order>);

  @override
  _i5.Future<_i2.Order> cancelOrder({
    required String? orderId,
    required String? reason,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [],
          {
            #orderId: orderId,
            #reason: reason,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<_i2.Order>.value(_FakeOrder_0(
          this,
          Invocation.method(
            #cancelOrder,
            [],
            {
              #orderId: orderId,
              #reason: reason,
              #notes: notes,
            },
          ),
        )),
      ) as _i5.Future<_i2.Order>);

  @override
  _i5.Future<_i3.Voucher> validateVoucher({
    required String? voucherCode,
    required String? shopId,
    required double? orderSubtotal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVoucher,
          [],
          {
            #voucherCode: voucherCode,
            #shopId: shopId,
            #orderSubtotal: orderSubtotal,
          },
        ),
        returnValue: _i5.Future<_i3.Voucher>.value(_FakeVoucher_1(
          this,
          Invocation.method(
            #validateVoucher,
            [],
            {
              #voucherCode: voucherCode,
              #shopId: shopId,
              #orderSubtotal: orderSubtotal,
            },
          ),
        )),
      ) as _i5.Future<_i3.Voucher>);

  @override
  _i5.Future<List<_i3.Voucher>> getAvailableVouchers({
    required String? shopId,
    required double? orderSubtotal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableVouchers,
          [],
          {
            #shopId: shopId,
            #orderSubtotal: orderSubtotal,
          },
        ),
        returnValue: _i5.Future<List<_i3.Voucher>>.value(<_i3.Voucher>[]),
      ) as _i5.Future<List<_i3.Voucher>>);
}
