// Mocks generated by Mockito 5.4.4 from annotations
// in ai_flutter/test/unit/features/cart/domain/use_cases/checkout_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:ai_flutter/core/models/cart_item.dart' as _i2;
import 'package:ai_flutter/core/models/order.dart' as _i3;
import 'package:ai_flutter/core/models/product.dart' as _i7;
import 'package:ai_flutter/core/models/voucher.dart' as _i4;
import 'package:ai_flutter/features/cart/domain/repositories/cart_repository.dart'
    as _i5;
import 'package:ai_flutter/features/cart/domain/repositories/order_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCartItem_0 extends _i1.SmartFake implements _i2.CartItem {
  _FakeCartItem_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrder_1 extends _i1.SmartFake implements _i3.Order {
  _FakeOrder_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoucher_2 extends _i1.SmartFake implements _i4.Voucher {
  _FakeVoucher_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i5.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.CartItem>> getCart(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getCart,
          [userId],
        ),
        returnValue: _i6.Future<List<_i2.CartItem>>.value(<_i2.CartItem>[]),
      ) as _i6.Future<List<_i2.CartItem>>);

  @override
  _i6.Future<List<_i7.Product>> getProductsForCart(List<String>? productIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsForCart,
          [productIds],
        ),
        returnValue: _i6.Future<List<_i7.Product>>.value(<_i7.Product>[]),
      ) as _i6.Future<List<_i7.Product>>);

  @override
  _i6.Future<_i2.CartItem> addToCart({
    required String? userId,
    required String? productId,
    String? variantId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [],
          {
            #userId: userId,
            #productId: productId,
            #variantId: variantId,
            #quantity: quantity,
          },
        ),
        returnValue: _i6.Future<_i2.CartItem>.value(_FakeCartItem_0(
          this,
          Invocation.method(
            #addToCart,
            [],
            {
              #userId: userId,
              #productId: productId,
              #variantId: variantId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i6.Future<_i2.CartItem>);

  @override
  _i6.Future<_i2.CartItem> updateQuantity({
    required String? cartItemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuantity,
          [],
          {
            #cartItemId: cartItemId,
            #quantity: quantity,
          },
        ),
        returnValue: _i6.Future<_i2.CartItem>.value(_FakeCartItem_0(
          this,
          Invocation.method(
            #updateQuantity,
            [],
            {
              #cartItemId: cartItemId,
              #quantity: quantity,
            },
          ),
        )),
      ) as _i6.Future<_i2.CartItem>);

  @override
  _i6.Future<void> removeCartItem(String? cartItemId) => (super.noSuchMethod(
        Invocation.method(
          #removeCartItem,
          [cartItemId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearCart(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> syncCart(
    String? userId,
    List<_i2.CartItem>? localItems,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncCart,
          [
            userId,
            localItems,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i8.OrderRepository {
  MockOrderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.Order>> createOrder({
    required String? userId,
    required List<_i2.CartItem>? items,
    required String? addressId,
    required String? paymentMethod,
    String? voucherCode,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [],
          {
            #userId: userId,
            #items: items,
            #addressId: addressId,
            #paymentMethod: paymentMethod,
            #voucherCode: voucherCode,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i6.Future<List<_i3.Order>>);

  @override
  _i6.Future<List<_i3.Order>> getOrders({
    required String? userId,
    String? status,
    int? limit,
    String? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #userId: userId,
            #status: status,
            #limit: limit,
            #cursor: cursor,
          },
        ),
        returnValue: _i6.Future<List<_i3.Order>>.value(<_i3.Order>[]),
      ) as _i6.Future<List<_i3.Order>>);

  @override
  _i6.Future<_i3.Order> getOrderDetail(String? orderId) => (super.noSuchMethod(
        Invocation.method(
          #getOrderDetail,
          [orderId],
        ),
        returnValue: _i6.Future<_i3.Order>.value(_FakeOrder_1(
          this,
          Invocation.method(
            #getOrderDetail,
            [orderId],
          ),
        )),
      ) as _i6.Future<_i3.Order>);

  @override
  _i6.Future<_i3.Order> cancelOrder({
    required String? orderId,
    required String? reason,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelOrder,
          [],
          {
            #orderId: orderId,
            #reason: reason,
            #notes: notes,
          },
        ),
        returnValue: _i6.Future<_i3.Order>.value(_FakeOrder_1(
          this,
          Invocation.method(
            #cancelOrder,
            [],
            {
              #orderId: orderId,
              #reason: reason,
              #notes: notes,
            },
          ),
        )),
      ) as _i6.Future<_i3.Order>);

  @override
  _i6.Future<_i4.Voucher> validateVoucher({
    required String? voucherCode,
    required String? shopId,
    required double? orderSubtotal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVoucher,
          [],
          {
            #voucherCode: voucherCode,
            #shopId: shopId,
            #orderSubtotal: orderSubtotal,
          },
        ),
        returnValue: _i6.Future<_i4.Voucher>.value(_FakeVoucher_2(
          this,
          Invocation.method(
            #validateVoucher,
            [],
            {
              #voucherCode: voucherCode,
              #shopId: shopId,
              #orderSubtotal: orderSubtotal,
            },
          ),
        )),
      ) as _i6.Future<_i4.Voucher>);

  @override
  _i6.Future<List<_i4.Voucher>> getAvailableVouchers({
    required String? shopId,
    required double? orderSubtotal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableVouchers,
          [],
          {
            #shopId: shopId,
            #orderSubtotal: orderSubtotal,
          },
        ),
        returnValue: _i6.Future<List<_i4.Voucher>>.value(<_i4.Voucher>[]),
      ) as _i6.Future<List<_i4.Voucher>>);
}
