// Mocks generated by Mockito 5.4.4 from annotations
// in ai_flutter/test/unit/features/home/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ai_flutter/core/models/category.dart' as _i7;
import 'package:ai_flutter/core/models/product.dart' as _i2;
import 'package:ai_flutter/core/models/product_variant.dart' as _i5;
import 'package:ai_flutter/core/models/review.dart' as _i6;
import 'package:ai_flutter/features/home/data/data_sources/product_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i3.ProductRemoteDataSource {
  MockProductRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Product>> fetchProducts({
    int? limit = 20,
    String? cursor,
    String? categoryId,
    Map<String, dynamic>? filters,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
          {
            #limit: limit,
            #cursor: cursor,
            #categoryId: categoryId,
            #filters: filters,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i4.Future<List<_i2.Product>>.value(<_i2.Product>[]),
      ) as _i4.Future<List<_i2.Product>>);

  @override
  _i4.Future<List<_i2.Product>> searchProducts({
    required String? query,
    int? limit = 20,
    String? cursor,
    Map<String, dynamic>? filters,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [],
          {
            #query: query,
            #limit: limit,
            #cursor: cursor,
            #filters: filters,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i4.Future<List<_i2.Product>>.value(<_i2.Product>[]),
      ) as _i4.Future<List<_i2.Product>>);

  @override
  _i4.Future<_i2.Product> fetchProductDetail(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProductDetail,
          [productId],
        ),
        returnValue: _i4.Future<_i2.Product>.value(_FakeProduct_0(
          this,
          Invocation.method(
            #fetchProductDetail,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Product>);

  @override
  _i4.Future<List<_i5.ProductVariant>> fetchProductVariants(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProductVariants,
          [productId],
        ),
        returnValue:
            _i4.Future<List<_i5.ProductVariant>>.value(<_i5.ProductVariant>[]),
      ) as _i4.Future<List<_i5.ProductVariant>>);

  @override
  _i4.Future<List<_i6.Review>> fetchProductReviews({
    required String? productId,
    int? limit = 20,
    String? cursor,
    int? rating,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProductReviews,
          [],
          {
            #productId: productId,
            #limit: limit,
            #cursor: cursor,
            #rating: rating,
          },
        ),
        returnValue: _i4.Future<List<_i6.Review>>.value(<_i6.Review>[]),
      ) as _i4.Future<List<_i6.Review>>);

  @override
  _i4.Future<List<_i7.Category>> fetchCategories() => (super.noSuchMethod(
        Invocation.method(
          #fetchCategories,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Category>>.value(<_i7.Category>[]),
      ) as _i4.Future<List<_i7.Category>>);

  @override
  _i4.Future<List<String>> fetchSearchSuggestions({
    required String? query,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSearchSuggestions,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}
